/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package service;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author H3rn4n
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(service.CompradorFacadeREST.class);
        resources.add(service.LocalFacadeREST.class);
        resources.add(service.PedidoFacadeREST.class);
        resources.add(service.PersonaFacadeREST.class);
        resources.add(service.PresupuestoFacadeREST.class);
        resources.add(service.RubroFacadeREST.class);
        resources.add(service.UsuarioFacadeREST.class);
        resources.add(service.VendedorFacadeREST.class);
        resources.add(service.mercadoPagoFacadeREST.class);
    }
    
}
