package com.security.fragments;

public enum FragmentContants{FRAGMENT_MAP,FRAGMENT_INVOICES, FRAGMENT_ORDERS, FRAGMENT_CONFIGURATION, FRAGMENT_BUDGET, FRAGMENT_FILTER,FRAGMENT_STORE,FRAGMENT_BUDGET_DETAIL, FRAGMENT_ORDER_DETAIL };


